#!/bin/bash

# DNS Fix Helper Script for OzBargain Telegram Bot
# This script helps diagnose and fix DNS resolution issues

echo "🔧 DNS Fix Helper Script"
echo "========================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ] && [ "$1" != "--check-only" ]; then 
    echo "⚠️  Some fixes require root privileges"
    echo "   Run: sudo $0"
    echo "   Or: $0 --check-only (for diagnosis only)"
    echo ""
fi

# Test 1: Check current DNS configuration
echo "1️⃣  Checking current DNS configuration..."
if [ -f /etc/resolv.conf ]; then
    echo "Current /etc/resolv.conf:"
    cat /etc/resolv.conf | grep -E "^nameserver" | head -5
    
    nameserver_count=$(grep -c "^nameserver" /etc/resolv.conf)
    if [ "$nameserver_count" -eq 0 ]; then
        echo "❌ No nameservers configured!"
    else
        echo "✓ Found $nameserver_count nameserver(s)"
    fi
else
    echo "❌ /etc/resolv.conf not found!"
fi
echo ""

# Test 2: Test DNS resolution
echo "2️⃣  Testing DNS resolution..."
domains=("api.telegram.org" "www.google.com" "www.ozbargain.com.au")
failed_domains=()

for domain in "${domains[@]}"; do
    if nslookup "$domain" > /dev/null 2>&1; then
        ip=$(nslookup "$domain" 2>/dev/null | grep -A1 "Name:" | grep "Address:" | awk '{print $2}' | head -1)
        echo "✓ $domain → $ip"
    else
        echo "❌ $domain → FAILED"
        failed_domains+=("$domain")
    fi
done
echo ""

# Test 3: Test with different DNS servers
echo "3️⃣  Testing with Google DNS (8.8.8.8)..."
if nslookup api.telegram.org 8.8.8.8 > /dev/null 2>&1; then
    echo "✓ Works with Google DNS"
    use_google_dns=true
else
    echo "❌ Still fails with Google DNS"
    use_google_dns=false
fi
echo ""

# Test 4: Check if Docker
echo "4️⃣  Checking environment..."
if [ -f /.dockerenv ]; then
    echo "✓ Running inside Docker container"
    in_docker=true
else
    echo "✓ Running on host system"
    in_docker=false
fi
echo ""

# Recommendations
echo "📋 Recommendations:"
echo "===================="

if [ ${#failed_domains[@]} -eq 0 ]; then
    echo "✅ All DNS tests passed! Your DNS is working correctly."
    echo ""
    echo "If you're still having issues with Telegram:"
    echo "1. Telegram might be blocked in your region"
    echo "2. Try using a VPN"
    echo "3. Check firewall settings"
    echo ""
    exit 0
fi

echo "⚠️  DNS resolution is failing for some domains"
echo ""

if [ "$in_docker" = true ]; then
    echo "Since you're in Docker, add this to your docker-compose.yml:"
    echo ""
    echo "services:"
    echo "  ozbargain-bot:"
    echo "    dns:"
    echo "      - 8.8.8.8"
    echo "      - 1.1.1.1"
    echo "      - 8.8.4.4"
    echo ""
    echo "Then rebuild: docker-compose down && docker-compose up -d --build"
else
    echo "OPTION 1: Add Google DNS to /etc/resolv.conf"
    echo "------------------------------------------"
    echo "Run these commands:"
    echo ""
    echo "  sudo bash -c 'echo \"nameserver 8.8.8.8\" > /etc/resolv.conf'"
    echo "  sudo bash -c 'echo \"nameserver 1.1.1.1\" >> /etc/resolv.conf'"
    echo ""
    
    echo "OPTION 2: Use systemd-resolved (if available)"
    echo "--------------------------------------------"
    if command -v systemd-resolve &> /dev/null || command -v resolvectl &> /dev/null; then
        echo "  sudo systemd-resolve --set-dns=8.8.8.8 --interface=eth0"
        echo "  sudo systemd-resolve --set-dns=1.1.1.1 --interface=eth0"
    else
        echo "  (systemd-resolved not available on this system)"
    fi
    echo ""
    
    echo "OPTION 3: Edit NetworkManager (if using it)"
    echo "-----------------------------------------"
    if command -v nmcli &> /dev/null; then
        echo "  nmcli con mod <connection-name> ipv4.dns \"8.8.8.8 1.1.1.1\""
        echo "  nmcli con up <connection-name>"
    else
        echo "  (NetworkManager not available on this system)"
    fi
fi

echo ""
echo "After making changes, test again with: npm test"
echo ""

# Quick fix option
if [ "$1" != "--check-only" ] && [ "$EUID" -eq 0 ]; then
    echo "Do you want to apply Google DNS fix now? (y/N)"
    read -r response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        echo "Backing up current resolv.conf..."
        cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)
        
        echo "Writing new DNS configuration..."
        cat > /etc/resolv.conf << EOF
# Generated by DNS fix script
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 8.8.4.4
EOF
        
        echo "✓ DNS configuration updated!"
        echo ""
        echo "Testing new configuration..."
        if nslookup api.telegram.org > /dev/null 2>&1; then
            echo "✅ SUCCESS! api.telegram.org now resolves correctly"
            echo ""
            echo "Run your bot now: npm start"
        else
            echo "❌ Still not working. There may be another issue."
            echo "Restoring backup..."
            mv /etc/resolv.conf.backup.$(date +%Y%m%d)* /etc/resolv.conf 2>/dev/null
        fi
    fi
fi

exit 0
